import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { OpenAPIObject, SwaggerCustomOptions } from '@nestjs/swagger';

/**
 * Swagger UI plumbing.
 *
 * The OpenAPI document itself is generated by `nestia swagger` from
 * the TypeScript types on the controller surface and committed to
 * apps/web/src/api/openapi-spec.json. This module is the runtime
 * adapter: it loads that spec from disk and ships the UI tuning
 * passed to SwaggerModule.setup.
 *
 * @nestjs/swagger stays as a runtime dependency for the UI middleware
 * only - the @ApiProperty / @ApiTags / DocumentBuilder surface is
 * gone, replaced entirely by typia tags on plain TypeScript types.
 */

export const OPENAPI_UI_PATH = 'docs';
export const OPENAPI_JSON_PATH = 'docs-json';

const SPEC_PATH = resolve(
  __dirname,
  '..',
  '..',
  '..',
  'apps',
  'web',
  'src',
  'api',
  'openapi-spec.json',
);

/**
 * Swagger UI behaviour tuned for fast comprehension of a small read
 * surface. See PR #136 for the rationale behind each option.
 */
const SWAGGER_UI_OPTIONS = {
  docExpansion: 'list' as const,
  filter: true,
  displayRequestDuration: true,
  displayOperationId: true,
  tryItOutEnabled: true,
  persistAuthorization: true,
  tagsSorter: 'alpha' as const,
  operationsSorter: 'alpha' as const,
  defaultModelsExpandDepth: 1,
  defaultModelExpandDepth: 2,
  syntaxHighlight: { theme: 'monokai' as const },
};

const SWAGGER_CUSTOM_CSS = `
  .swagger-ui .topbar { display: none; }
  .swagger-ui .info { margin: 24px 0 32px; }
  .swagger-ui .info .title { color: #4c1d95; font-weight: 700; }
  .swagger-ui .scheme-container { box-shadow: none; padding: 12px 0; }
  .swagger-ui .opblock-tag { font-size: 18px; border-bottom: 1px solid #ede9fe; }
  .swagger-ui .opblock.opblock-get { border-color: #2563eb; background: #eff6ff; }
  .swagger-ui .opblock.opblock-get .opblock-summary-method { background: #2563eb; }
  .swagger-ui .btn.execute { background: #4c1d95; border-color: #4c1d95; }
`;

export const SWAGGER_CUSTOM_OPTIONS: SwaggerCustomOptions = {
  jsonDocumentUrl: OPENAPI_JSON_PATH,
  useGlobalPrefix: true,
  customSiteTitle: 'SPS API · Docs',
  customCss: SWAGGER_CUSTOM_CSS,
  swaggerOptions: SWAGGER_UI_OPTIONS,
};

/**
 * Load the OpenAPI document produced by `pnpm openapi:dump`
 * (which now wraps `nestia swagger`). Returns null when the file is
 * absent, so a fresh checkout that has not yet run the dump just
 * skips the docs route instead of crashing the api at startup.
 */
export function loadOpenApiDocument(): OpenAPIObject | null {
  try {
    const raw = readFileSync(SPEC_PATH, 'utf8');
    return JSON.parse(raw) as OpenAPIObject;
  } catch {
    return null;
  }
}
